version: '3.8'

services:
    todolist.pgsql:
        image: postgres:12.4-alpine
        container_name: pgsql-ATM
        restart: always
        ports:
            - "5435:5432"
        environment:
            - POSTGRES_PASSWORD=123qwe
            - POSTGRES_DB=accountingtm
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./docker/db:/var/lib/postgresql/data/pgdata